name: Backend CI/CD

on:
  push:
    paths:
      - 'backend/**'
    branches:
      - main
  pull_request:
    paths:
      - 'backend/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js for backend
        uses: actions/setup-node@v3
        with:
          node-version: 22.5.1

      - name: Install backend dependencies
        run: |
          cd backend
          npm install

      - name: Run lint check
        run: |
          cd backend
          npm run lint  # Ini akan gagal jika ada warning

      - name: Build backend
        if: github.ref == 'refs/heads/main'
        run: |
          cd backend
          npm run build
